import glob
from setuptools import setup
from pybind11.setup_helpers import Pybind11Extension
from pathlib import Path

__version__ = "0.0.1"

ext_modules = [
    Pybind11Extension(
        "frcLogLens_cpp",
        glob.glob("src/cpp/**.cpp", recursive=True),
        include_dirs=["src/include/"],
    ),
]

this_directory = Path(__file__).parent
long_description = (this_directory / "README.md").read_text()

setup(
    name="frcLogLens",
    version=__version__,
    install_requires=["robotpy-wpiutil>=2023"],
    authors=["Thomas Anderson", "Test Test"],
    author_emails=["tande92834@gmail.com", "test@test.com"],
    url="https://github.com/Team997Coders/frcLogLens",
    description="A utility for large-scale analysis of standard data logs generated by \
        robots in the FIRST Robotics Competition.",
    long_description=long_description,
    long_description_content_type="text/markdown",
    package_dir={"": "./src/py"},
    packages=["logLens"],
    ext_modules=ext_modules,
    python_requires=">=3.7",
    license="License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
)
